backend:
  name: git-gateway
  branch: main # اسم الفرع الرئيسي في GitHub

publish_mode: editorial_workflow 
media_folder: "assets/img" # مكان حفظ الصور اللي هترفعها

collections:
  - name: "cases" # الاسم البرمجي (لاتغيره)
    label: "ملفات القضايا" # اسم القائمة في لوحة التحكم
    folder: "_cases" # المجلد الذي سيتم حفظ القضايا فيه
    create: true # السماح بإنشاء قضايا جديدة
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # صيغة اسم الملف

    fields: # حقول النموذج الذي ستكتب فيه القضية
      - {label: "عنوان القضية", name: "title", widget: "string"}
      - {label: "تاريخ القضية", name: "date", widget: "datetime", format: "YYYY-MM-DD"} # إضافة التاريخ
      - {label: "حالة القضية", name: "status", widget: "select", options: ["قيد التحقيق", "تم الكشف"], default: "قيد التحقيق"}
      - {label: "ملخص قصير", name: "summary", widget: "text"}
      - {label: "صورة الغلاف (مفتاح القضية)", name: "featured_image", widget: "image", required: false}
      - {label: "تفاصيل القضية الكاملة", name: "body", widget: "markdown"} # هذا يسمح لك بإضافة العناوين والصور والنصوص