backend:
  name: git-gateway
  branch: main # اسم الفرع الرئيسي في GitHub

publish_mode: editorial_workflow # يسمح بمراجعة القضايا قبل النشر
media_folder: "assets/img" # مكان حفظ الصور اللي هترفعها

collections:
  - name: "cases" # الاسم البرمجي
    label: "ملفات القضايا" # اسم القائمة في لوحة التحكم
    folder: "_cases" # المجلد الذي سيتم حفظ القضايا فيه
    create: true # السماح بإنشاء قضايا جديدة
    slug: "{{slug}}" # إعدادات اسم الملف

    fields: # حقول النموذج الذي ستكتب فيه القضية
      - {label: "عنوان القضية", name: "title", widget: "string"}
      - {label: "حالة القضية", name: "status", widget: "select", options: ["قيد التحقيق", "تم الكشف"], default: "قيد التحقيق"}
      - {label: "ملخص قصير", name: "summary", widget: "text"}
      - {label: "تفاصيل القضية الكاملة", name: "body", widget: "markdown"} # يسمح بالكتابة بخط عريض ووضع صور
      - {label: "صورة الغلاف (مفتاح القضية)", name: "featured_image", widget: "image", required: false}